MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: './Outputs/x101_ncp/new_model.pth'
  BACKBONE:
    CONV_BODY: "R-101-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STRIDE_IN_1X1: False
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    TRANS_FUNC: "BottleneckWithFixedBatchNorm"
    STEM_FUNC: "StemWithFixedBatchNorm"
    STAGE_WITH_DCN: (False, True, True, True)
    WITH_MODULATED_DCN: True
    DEFORMABLE_GROUPS: 1
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    FPN_POST_NMS_TOP_N_TRAIN: 4000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  FPN:
    USE_GN: True
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPNXconv1fc_panet_FeatureExtractor"
    PREDICTOR: "FPNPredictor"
    USE_GN: True
    NUM_CLASSES: 27
  ROI_MASK_HEAD:
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    FEATURE_EXTRACTOR: "MaskRCNNFPN_adp_ff_FeatureExtractor"
    PREDICTOR: "MaskRCNN_panet_Predictor"
    POOLER_RESOLUTION: 14
    POOLER_SAMPLING_RATIO: 2
    RESOLUTION: 28
    DILATION: 1
    SHARE_BOX_FEATURE_EXTRACTOR: False
    USE_GN: True
  MASK_ON: True
DATASETS:
  TRAIN: ("coco_custom_train",)
  TEST: ("coco_custom_val",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
  BASE_LR: 0.02
  WEIGHT_DECAY: 0.0001
  STEPS: (2000, 2600)
  MAX_ITER: 3000
  IMS_PER_BATCH: 16
  CHECKPOINT_PERIOD: 500 
INPUT:
  MIN_SIZE_TRAIN: (1200, 1200, 1000, 800, 600, 400) # (800,)
  MAX_SIZE_TRAIN: 1400
  MIN_SIZE_TEST: 1000
  MAX_SIZE_TEST: 1400
OUTPUT_DIR: './Outputs/x101_ncp'
